apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsp-artifacts
  namespace: fabric-shortcut-proxy
  labels:
    app.kubernetes.io/part-of: fabric-shortcut-proxy
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
