apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fabric-shortcut-proxy
resources:
  - namespace.yaml
  - artifact-pvc.yaml
  - common-configmap.yaml
  - python-statefulset.yaml
  - cpp-deployment.yaml
  - cpp-service.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
