apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - artifact-pvc.yaml
  - common-configmap.yaml
  - manager-deployment.yaml
  - manager-service.yaml
  - python-headless-service.yaml
  - python-statefulset.yaml
  - cpp-deployment.yaml
  - cpp-service.yaml
  - cpp-hpa.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
