apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fsp-cpp-agent
  namespace: fabric-shortcut-proxy
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fsp-cpp-agent
