apiVersion: v1
kind: Service
metadata:
  name: fsp-materializer
  namespace: fabric-shortcut-proxy
  labels:
    app.kubernetes.io/name: fsp-materializer
    app.kubernetes.io/part-of: fabric-shortcut-proxy
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: fsp-materializer
  ports:
    - name: health
      port: 9000
      targetPort: health
