apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - artifact-pv.yaml
  - postgres.yaml
  - source-secret.yaml
  - smoke-client.yaml
  - stunnel-configmap.yaml
  - manager-control-network-policy.yaml
patches:
  - path: artifact-pvc-patch.yaml
  - path: python-statefulset-kind-patch.yaml
  - path: cpp-deployment-kind-patch.yaml
  - path: cpp-hpa-delete.yaml
  - path: manager-deployment-tls-patch.yaml
  - path: manager-service-tls-patch.yaml
  - path: python-statefulset-tls-patch.yaml
  - path: cpp-deployment-tls-patch.yaml