apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsp-artifacts-kind
  labels:
    app.kubernetes.io/part-of: fabric-shortcut-proxy
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /var/local/fsp-artifacts
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - fsp-proof-control-plane
