apiVersion: v1
kind: Secret
metadata:
  name: fsp-source
  namespace: fabric-shortcut-proxy
type: Opaque
stringData:
  DB_URL: postgresql+asyncpg://fsp_reader:replace-me@postgres.example.internal:5432/source_db
